fluidkeys/fluidkeys

- src/fluidkeys.go
When running `gpg --version` on a mac, it outputs:
```
gpg (GnuPG/MacGPG2) 2.2.8
libgcrypt 1.8.3
Copyright (C) 2018 Free Software Foundation, Inc.
```
This didn't fit the regex we were using.
> Modify the regex statement to work on MacGPG

- Makefile
We don't actually need this yet because we've only got 1 file for the
main package, but I made it so whatever.
> Makefile: factor out fluidkeys/main.go

- script/publish_latest_tag
1. set GOPATH to a temp directory
2. clone fluidkeys into GOPATH/src/github.com/fluidkeys/fluidkeys
When `script/publish-latest_tag` runs, it makes a fresh `git clone` of
the repo, then `cd`s there and runs `make` etc.
Because of the way Go workspaces work, if we want to import local
packages (e.g. `backupzip`, `pgpkey` etc) by doing:
```
import "github.com/fluidkeys/fluidkeys/pgpkey"
```
... then our own `fluidkeys` repo *must* be checked out into
`$GOPATH/src/github.com/fluidkeys/fluidkeys`
> Jenkins: clone repo into Go workspace

- README.md
- script/publish_latest_tag
Rather than the root of download.fluidkeys.com which we'll probably want to
use for something else, like an instructions page.
And lots of fixes:
* `make install` into REPO_DIR not WORKSPACE
* Use reprepro in WORKSPACE not REPO_DIR
* Control cleanup with CLEAN_UP=1|0
* Apt repo: delete remote files if they don't exist
> Move apt to download.fluidkeys.com/desktop/apt

- .travis.yml
- Makefile
- README.md
- script/test_make_compile
On Jenkins and when installed via Homebrew, we don't know that the repo has
been checked out into `$GOPATH/src/github.com/fluidkeys/fluidkeys`
(brew unpacks a tarball into a temp directory, for example).
So, make a temporary directory, fake `GOPATH` and do some copying &
symlinking to ensure $GOPATH/src contains all the dependencies (external
and internal) that fluidkeys relies on.
This is not pretty, but I don't know a better way at the moment.
I've updated script/test_make_compile to test `make compile` in a temp dir.
Also remove `make install_dependencies`
We commit these into `vendor` now. `make install_dependencies` was from the
time when you had to run `go get ...`, which we no longer need.
Further, we definitely shouldn't run `dep` from `make compile` since we
want to compile the …
> Ensure `make compile` works from any location

- Gopkg.lock
- Gopkg.toml
I can see that it's going to get complicated maintaining a fork of
golang/crypto where some bits of functionality are in our fork, some
bits are in upstream, etc.
I already need to make another tweak in our fork (todo with revocation
certificates). I'm probably going to have to make a custom branch which
is encrypt-private-key + revocation-certificate
... so how should `fluidkeys` depend on `crypto` ?
My best suggestion at the moment is that we make whatever whacky
branches we need for a particular combination of commits at a given
time, and *tag* that branch with a date eg `2018-08-22` then point
fluidkeys to that.
I've tagged the crypto repo with that date, pointing to the tip of
`encrypt-private-keys`. Then, if I want to cherry-pick on a commit
related to revocation certificates, I can …
> fluidkeys/crypto : depend on tagged version

- fluidkeys/main.go
This allows you to run e.g.
```
FLUIDKEYS_DIR=/tmp/fluidkeys fk
```
... and config / backups will be stored there instead of in the home
directory.
> Use FLUIDKEYS_DIR if set (not ~/.config/fluidkeys)

- database/database.go
- database/database_test.go
- fingerprint/fingerprint.go
- fingerprint/fingerprint_test.go
- fluidkeys/main.go
- fluidkeys/main_test.go
- gpgwrapper/gpgwrapper.go
- gpgwrapper/gpgwrapper_test.go
- gpgwrapper/parser.go
- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
This Fingerprint parses and outputs the numerous valid formats of an OpenPGP
key fingerprint:
* 20 bytes: {0xA9, 0x99, 0xB7, 0x49, 0x8D, 0x1A, 0x8D, 0xC4, 0x73, 0xE5, 0x3C, 0x92, 0x30, 0x9F, 0x63, 0x5D, 0xAD, 0x1B, 0x55, 0x17}
* hex string: `A999B7498D1A8DC473E53C92309F635DAD1B5517`
* hex string: `0xA999B7498D1A8DC473E53C92309F635DAD1B5517`
* human "friendly" string: `A999 B749 8D1A 8DC4 73E5  3C92 309F 635D AD1B 5517`
This PR also replaces numerous uses of `string` with `Fingerprint`.
@idrysdale thanks for doing 90% of the work on database.go. The trick was to
stop trying to Json marshal / unmarshal a Fingerprint class, and rather define
that as a string:
* Parse it with [fingerprint.Parse](https://github.com/fluidkeys/fluidkeys/commit/4ad33e933780be783b76e4906784d72e14b1b5dd#diff-a8d1aea …
> Add `Fingerprint` class, use instead of string

- fingerprint/fingerprint.go
- fingerprint/fingerprint_test.go
`strings.TrimLeft` trims *any* of `0x` so it breaks keys starting with 0
`strings.TrimPrefix` trims *the exact* `0x`, which is what we want.
> fingerprint: Fix bug with leading `0x`

- colour/colour.go
- keytableprinter/formatwarnings.go
- keytableprinter/formatwarnings_test.go
FormatKeyWarningLines takes a status.KeyWarning and returns an array of human friendly messages coloured appropriately for printing to the terminal.
> Introduce keytableprinter.FormatKeyWarningLines

- assert/equality.go
- colour/colour.go
- colour/colour_test.go
- keytableprinter/formatwarnings.go
- keytableprinter/formatwarnings_test.go
- keytableprinter/keytableprinter.go
- keytableprinter/keytableprinter_test.go
Bit of a biggie this. Introducing the warnings opened a bit of a can of worms, since now we have columns of different lengths for keys.
I ended up refactoring `keytableprinter` to deal with this, which also resulted in some neater tests.
> Show warnings in key list table

- colour/colour.go
- colour/constants.go
This way, it'll be harder for the two lists of colour codes to go out of
sync (e.g. adding a colour code to `constants.go` and not realising it
*also* must be added to `StripAllColourCodes`)
> Simplify StripAllColourCodes

- gpgwrapper/gpgwrapper.go
- gpgwrapper/gpgwrapper_test.go
To make it work, make runWithStdin return stdoutAndStdErr even on error
It's important for calling functions to be able to inspect stdout and
stderr to work out *why* GnuPG failed.
It would have been possible to parse `err.Error()` but it seems much more
direct to work on stdout and stderr directly.
Possible future improvement: return (stdout, stderr, exitcode) instead?
> add gpgwrapper.GnuPG.ExportPrivateKey & tests

- keytableprinter/formatwarnings.go
- keytableprinter/formatwarnings_test.go
- status/keywarning.go
- status/status.go
* Change KeyWarning interface to a KeyWarning struct with a WarningType field
* Rename:
- DueForRotation     -> PrimaryKeyDueForRotation
- OverdueForRotation -> PrimaryKeyOverdueForRotatin
- Expired            -> PrimaryKeyExpired
- NoExpiry           -> PrimaryKeyNoExpiry
- LongExpiry         -> PrimaryKeyLongExpiry
* Add Subkey warning types
- NoValidEncryptionSubkey
- SubkeyDueForRotation
- SubkeyOverdueForRotation
- SubkeyNoExpiry
- SubkeyLongExpiry
Note that the subkey warnings stray a bit from our design document: we haven't
really decided whether to hide or suppress any mention of subkeys...
Note that this currently causes duplication where the primary key and subkey
both produce the same warning message.
> Refactor KeyWarning

- pgpkey/pgpkey.go
This was missing, and swallowed a bug, causing a huge rabbit hole!
> PgpKey: add error handling in Armor[Private]

- assert/equality.go
- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
- policy/policy.go
- policy/policy_test.go
- status/status.go
- status/status_test.go
* split status package into status & policy
status was logically doing 2 things:
1. defining the "policy" e.g. when to rotate keys, define expiry etc 2.
testing against, and enforcing the policy, e.g. "this key's expiry is too
long"
I realised this when I tried to point PgpKey.Generate at status'
NextExpiryTime function and got a circular import[1]
I think what we *actually* want is a separate "policy" package which
defines the rules, and have status just enforce them. Then, PgpKey can ask
the policy package for the expiry it should use.
I think the policy package will also be a perfect place to define the
ciphers, hashes, compression preferences[2]
[1]:
https://trello.com/c/KfZguoBa/182-when-we-make-a-new-key-set-its-expiry-to-the-next-rotation-time-not-60-days
[2]: …
> PgpKey.Generate: set expiry according to (new) policy

- status/actions.go
- status/actions_test.go
- status/keyactions.go
This is the core of the key rotation code - for a given `KeyWarning`, define
a `KeyAction` that remedies that situation.
For discussion: should a subkey that's overdue for rotation be revoked (and
another subkey created) or should its expiry be shortened?
> add MakeActionsFromKeyWarnings() function and tests

- exampledata/exampledata.go
- exampledata/exampledata_test.go
- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
- status/status.go
- status/status_test.go
Rather than using the ExamplePublicKey4, whcih relied on *real-world* now
rather than a test now, use ExamplePrivateKey2 and tweak its subkey and
primary key expiration times in the test.
* rename & export `PgpKey.updateSubPgpKeyExpiryToNow` as `PgpKey.UpdateSubPgpKeyValidUntil`
* pgpkey:EncryptionSubkey: take optional `now` arg
* delete ExamplePublicKey4
- it has a short expiry date, so it has now expired (the test was written
to depend on *real* now rather than passed-in `now`)
- the private key is not committed, so I'm unable to edit the key :(
> fix broken TestGetEncryptionSubkeyWarnings

- assert/equality.go
- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
- policy/policy.go
I've more or less followed the Riseup OpenPGP best practice document.
Note that only *new* keys get these preferences — we don't set the prefs for
previously generated keys (yet).
> pgpkey.Generate: set cipher/hash/compression prefs

- openpgpdefs/compression/compression.go
- openpgpdefs/hash/hash.go
- openpgpdefs/symmetric/symmetric.go
- policy/policy.go
This defines constants from RFC 4880 and RFC 5881 for symmetric key
algorithms, hash algorithms and compression algorithms.
The reason for defining these is that openpgp.packet is incomplete: for
example it doesn't define any bytes that it can't support (like BZIP2).
That matters because we want to be able to *test* for BZIP2 in imported
keys to warn that it's not usable.
> add openpgpdefs subpackage

- fluidkeys/main.go
Factoring out the global variable in 58d15f03 broke things.
> Fix the fact fluidkeysDirectory was never set

- backupzip/backupzip.go
- backupzip/backupzip_test.go
- fluidkeys/main.go
This subdirectory is created from the date at which the backup is created (as opposed to the key's slug, which is the date at which the key was created).
We also now print the full path of the backup directory, rather than just the fluidkeys directory.
> Start storing backups in date-stamped subdirectories

- colour/colour.go
- fluidkeys/keyrotate.go
- fluidkeys/main.go
For each key we now print a list of the warnings followed by the actions
that Fluidkeys will carry out, e.g:
```
6 warnings for test@example.com
▸   Primary key overdue for rotation, expires in 11 days
▸   Encryption subkey overdue for rotation, expires in 11 days
▸   Primary key has weak preferred symmetric algorithms (AES256, AES192, AES128, TripleDES)
▸   Primary key has weak preferred hash algorithms (SHA512, SHA384, SHA256, SHA224, SHA1)
▸   Primary key missing uncompressed preference
▸   Primary key has unsupported preferred compression algorithm (BZIP2)
[ ] Extend the primary key expiry to 1 Dec 18
[ ] Set preferred encryption algorithms to AES256, AES192, AES128, CAST5
[ ] Set preferred hash algorithms to SHA512, SHA384, SHA256, SHA224
[ ] Set preferred compression algorithms to …
```
> Format `key rotate` in line with the new designs

- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
- status/status_test.go
(rebase after merging #135)
previously `validUntil` was being used as the signature `CreationTime`.
That's a trap: if you updated the validity to the years in the future, the
future-dated signature would override any new signatures trying to shorten
the subkey expiry (because the future-dated signature would always be the
"newest")
> fix UpdateSubkeyValidUntil — pass in `now` arg

- fluidkeys/keyrotate.go
This ensures the user will always have a backup to disk of their latest
keys. Note: if a user imports a key from GPG into Fluidkeys and
Fluidkeys subsequently makes any changes to this key, it'll then go on
to back this up to disk, too. It does this automatically.
> Backup all modified keys on `key rotate`

- fluidkeys/main.go
note that I've gone for capitalisation now because it makes it feel more
like a global (and it doesn't conflict with the lowercase `config`
package name)
> load Config in main init()

- keyring/keyring.go
- keyring/passwordfile.go
(merge after merging #148)
workaround for this bug:
https://trello.com/c/iwwtzNbt/223-on-macos-keychain-access-prompts-every-time-fluidkeys-tries-to-access-a-password
if specified in the environment, read passwords from the given TOML file
and attempt to use them before looking in the keyring.
this enables people to start using automated (cron) key rotation if they
choose to, before we fix the issue with Keychain Access
> read passwords from FLUIDKEYS_PASSWORDS_TOML_FILE

- config/config.go
- config/config_test.go
As part of this, improve Config class
* allow different Fingerprint formats
* panic if an invalid fingerprint is found
* panic if an unrecognised config variable is encountered
* change store_password default to false
> add Config.ShouldRotateAutomatically & tests

- gpgwrapper/gpgwrapper.go
if gpg complains about exporting a key due to an empty password, treat
that the same way as if it were a non-empty invalid password
> gpgwrapper: treat "no password" as bad password

- Gopkg.lock
- Gopkg.toml
- Makefile
- script/test_dep_gopkg_files
* run `dep ensure`, fix Gopkg.lock
I think my `dep` command on my desktop is older than yours @idrysdale and
the one on my laptop.
Running `dep ensure` fixed these issues:
``` github.com/BurntSushi/toml: imported or required, but missing from
Gopkg.lock's input-imports github.com/docopt/docopt-go: imported or
required, but missing from Gopkg.lock's input-imports
github.com/fluidkeys/crypto/openpgp: imported or required, but missing from
Gopkg.lock's input-imports github.com/fluidkeys/crypto/openpgp/armor:
imported or required, but missing from Gopkg.lock's input-imports
github.com/fluidkeys/crypto/openpgp/errors: imported or required, but
missing from Gopkg.lock's input-imports
github.com/fluidkeys/crypto/openpgp/packet: imported or required, but
missing from Gopkg.lock's input-imports …
```
> fix Gopkg.* and check for issues in `make test`

- archiver/archiver.go
- archiver/archiver_test.go
- backupzip/backupzip.go
- backupzip/backupzip_test.go
- fluidkeys/keyrotate.go
Rather than just put backup zips in subdirectories of dates, we now put the
time stamp on the end of each file.
i.e: `/backups/2018-10-19/gpghome-110713.tgz`
> Timestamp all file backups

- .github/ISSUE_TEMPLATE.md
I've made this as an issue template so that users would-be bug reporters
see the link to Trello inline, right after they start to create a new
issue.
I prefer this to asking reporters to go and read 2 separate documents
(contributing guide), since we don't have anything more to say yet.
> add ISSUE_TEMPLATE.md, signposting our Trello

- .github/ISSUE_TEMPLATE.md
the template shows up as unrendered Markdown so it's easier to split out the URL
> make URL easier to copy in ISSUE_TEMPLATE

- fluidkeys/init.go
- fluidkeys/keycreate.go
- fluidkeys/main.go
- out/out.go
* log command-line to log, e.g. `$ fk key create`
* log all `out.Print` output
* don't log passwords (use a special character to suppress certain lines)
> log most output to `debug.log`

- Gopkg.lock
- fluidkeys/keycreate.go
- keyring/keyring.go
- keyring/keyring_test.go
- vendor/github.com/fluidkeys/keyring/keyring.go
This involved updating `fluidkeys/keyring` to return the Backendtype.
> Tell the user which keyring their password is stored in

- Makefile
- README.md
- script/test_make_compile
I tried for a long time to ensure `make compile` works *even if* you've
cloned the repo outside your GOPATH. This has caused a lot of problems
and I'm giving up.
This was to make it easy for external compile scripts like Jenkins and
Homebrew. I suspect this is going to break our deployment, so we'll have
to figure out how to fix them separately.
> Don't support compile from clone outside GOPATH

- config/config.go
- config/config_test.go
This will allow the user to mark keys to be uploaded to the Fluidkeys
directory, thus allowing them to be able to be searched for by email
address.
> Add `allow_search_by_email` to config for each key

- Makefile
It was messing with the Arch package installation.
> `make compile`: don't run `clean` first

- api/api.go
This is necessary, else `clearsign.Encode` will blow up.
> Ensure signText must be passed a decrypted private key

- fluidkeys/keycreate.go
This reverts commit 1475e25585446038d5d84fb49e3e774c52a64533.
This wasn't supposed to be added here: we guard elsewhere in `signText`:
d47c19fbef2d6f67bb03e1d8d06e0
> Revert "Guard tryToPublishKeyAndSetAllowSearchByEmail"

- fluidkeys/keycreate.go
- fluidkeys/keymaintain.go
- fluidkeys/keypublish.go
* Separate out setting config and publishing key
* add PublishKeyToAPI KeyAction, no prompt in maintain
instead of running custom code inside `key maintain`, just insert another
KeyAction (similar to BackupToZIP) if the config allows.
* Check error on (keyPublish) > publishKeyToAPI and print
* reword "API" -> "Fluidkeys directory"
* move promptAndTurnOnPublishToAPI
> Refactor publish to API inside key maintain

- fluidkeys/secretsend.go
We're abusing our pattern where we hint the user what to do next by
showing them a command for someone *else*.
> Drop "Tell them to get it by running:"

- keyring/keyring.go
When running from crontab *without* forcing the Keychain to "login", the
keyring comes back with no password because it defaults to looking in
the *system* keyring.
> set KeychainName to "login" on macOS Keychain

- fluidkeys/init.go
- gpgwrapper/backup_test.go
- gpgwrapper/gpgwrapper.go
- gpgwrapper/gpgwrapper_test.go
* search for gpg binary in predefined directories
Don't use PATH as this is a route for an attacker to manipulate Fluidkeys
into revealing a password to a (fake) gpg binary by manipulating PATH
* make gpgwrapper.Load, add GnuPG.fullGpgPath
* make makeGpgWithTempHome test helper
* move constants to bottom of file
> find gpg2 binary from fixed PATHs

- fluidkeys/main.go
Namely:
* Remove the redundant case of 'init' command
* Return exitCode from secretSubcommand to caller (rather than exiting from there)
* Remove a stray line of commented code
* Correctly indent code (don't use spaces)
> clean up main package

- fluidkeys/secretreceive.go
- out/out.go
* out.Print: redact *all* lines with NoLogCharacter
out.Print gets a multi-line `message`, redact the whole message rather than
just the single line containing the NoLogCharacter.
This allows us to insert the NoLogCharacter in the header line of the
secret snippet, without having to modify the actual secret lines at all
(good for copy/pasting etc)
* [WIP] add NoLogCharacter to secret snippet output
Note that I've used a "1+" fudge factor here
* `len(NoLogCharacter) = 4` (bytes)
* `len([]rune(NoLogCharacter)) = 1` (rune)
* actual *display width* in characters = 2
This isn't very elegant. I'm currently not sure how to calculate the length
a better way.
> WIP: Don't log content of secret snippet

- fluidkeys/keycreate.go
- fluidkeys/main.go
- fluidkeys/setup.go
This will allow us to direct people to install Fluidkeys by running:
```
fk setup ian@example.com
```
Something odd appears to be happening with docopts. `fk setup [<email>]`
should allow an optional argument `email` to be passed to `setup`, however,
args.String("<email>") returns an error.
> Allow optional email to be passed to setup

- Makefile
- fluidkeys/keymaintain.go
- fluidkeys/keyupload.go
- fluidkeys/main.go
- fluidkeys/secretreceive.go
- keytable/keytable.go
- status/keywarning.go
- status/keywarning_test.go
You upload your key to Fluidkeys, so that you can receive secrets.
We don't talk about publishing because it implies it's being made public,
it's only available to be searched by email.
> `key publish` > `key upload`

- fluidkeys/keycreate.go
the `:=` operator meant `email` was shadowing the command-line argument
`email`
(Damn I wish Go would fail on *all* shadowing, this so reminds me of C++
days)
> don't make keys with an empty email address

- gpgwrapper/gpgwrapper.go
on macOS, when gpg is installed from homebrew, it seems there's no
binary or symlink called `gpg2`, so we can't rely on looking for that.
Instead, look for `gpg2` or `gpg` but also check that the version string
comes back as "2.*"
fixes #276
> look for `gpg` binary as well as `gpg2`

- fluidkeys/privatekeys.go
- fluidkeys/privatekeys_test.go
- gpgwrapper/gpgwrapper.go
- gpgwrapper/gpgwrapper_test.go
- gpgwrapper/interfaces.go
I'm not sure why this was ever being returned. It doesn't contain anything
very useful, and it was never used by any callers!
> gpg.ImportArmoredKey: return err not (stdout, err)

- fluidkeys/main.go
- scheduler/scheduler.go
e.g. when `run_from_cron = true` and at least one key has `maintain_automatically = true`
Don't go adding ourselves to crontab until there's actually a need to. It's
pretty alarming to do that on the very first command someone types, e.g.
`fk secret send`
This probably isn't the end of the story: we should consider how we explicitly ask to modify
the user's crontab, but I'd like to see whether people find this approach
more reasonable first.
Also, don't use `crontab -r` to delete an empty crontab
if we remove our lines from the crontab and it results in the crontab being
empty, don't use `crontab -r` to remove it, just add an empty crontab.
this helps #274 where `systemd-cron-next` doesn't support `crontab -r`
> only modify crontab when actually necessary

- Makefile
- cmd/fk/main.go
- fk/errors.go
- fk/init.go
- fk/keycreate.go
- fk/keycreate_test.go
- fk/keyfromgpg.go
- fk/keymaintain.go
- fk/keyupload.go
- fk/main.go
- fk/main_test.go
- fk/password.go
- fk/privatekeys.go
- fk/privatekeys_test.go
- fk/secretreceive.go
- fk/secretsend.go
- fk/secretsend_test.go
- fk/setup.go
- fk/ui.go
* move all of `fk` code out of `fluidkeys/*.go` (`master` package) and
into `./fk/*.go`
* make a new `cmd/fk/main.go` which *only* passes through to `fk.Main()`
* simplify `Makefile`: build now requires single file `cmd/fk/main.go`
> factor out top-level fk code into `fk` package

- Gopkg.lock
- Gopkg.toml
- fk/secretreceive.go
- vendor/github.com/atotto/clipboard/.travis.yml
- vendor/github.com/atotto/clipboard/LICENSE
- vendor/github.com/atotto/clipboard/README.md
- vendor/github.com/atotto/clipboard/clipboard.go
- vendor/github.com/atotto/clipboard/clipboard_darwin.go
- vendor/github.com/atotto/clipboard/clipboard_unix.go
- vendor/github.com/atotto/clipboard/clipboard_windows.go
- vendor/github.com/atotto/clipboard/go.mod
Following the designs on the [Command Line Google Doc](https://docs.google.com/document/d/1FHQXHP7X8Uvtvn72OqZNVYyFMocrJ2MM1zWtYTM4d0c/#heading=h.435am9i821s9) `secret receive` now prints the number of secrets each key is receiving (and no longer list them numerically). It then iterates over each secret, prompting the user whether they want to copy the contents to the clipboard, then whether they want to delete it.
I opted to introduce https://github.com/atotto/clipboard/ to handle copying to the clipboard. It handles unix, with a friendly error message if they don't have a command
line tool installed:
> Iterate over the secrets on `secret receive`

- fk/secretreceive.go
- fk/secretreceive_test.go
* refactor (back) decryptAPISecret: return secret
since we no longer use sentToFingerprint, the pattern of passing in a
half-populated `secret` doesn't make sense any more. Just return it from
decryptAPISecret.
> remove unused secret.sentToFingerprint

- colour/colour.go
- fk/secretreceive.go
- fk/secretreceive_test.go
- pgpkey/decrypt.go
Following the designs on the [Command Line Google Doc](https://docs.google.com/document/d/1FHQXHP7X8Uvtvn72OqZNVYyFMocrJ2MM1zWtYTM4d0c/#heading=h.435am9i821s9) `secret receive` will now recieve secrets sent as files! 🙌
It will save files in `~\Downloads` and report an error if this directory doesn't exist.
If the file already exists, it'll attempt to increment a counter to find a filepath that doesn't exist. So if trying to download `README.md` and that file already exists, it'll suggest `README(1).md`.
Resulting interface:
Rebase after https://github.com/fluidkeys/fluidkeys/pull/293
> Prompt to save a secret to disk when receiving a file

- fk/secretreceive.go
- fk/secretreceive_test.go
- fk/secretsend.go
- fk/secretsend_test.go
* add all-new tests for getSecretFromStdin
convert scanUntilEOF -> stdinReader.scanUntilEOF(), adding a scanUntilEOFInterface for mocking
* also use new isValidTextSecret from secret receive to be consistent across both and send receive
> validate secret *before* previewing to screen

- fk/secretsend.go
- fk/secretsend_test.go
add a new `readUpTo` function which returns []byte from an `io.Reader` but only up to `maxBytes`.
Use this new `readUpTo` in both getSecretFromStdin and getSecretFromFile
> secret send: limit input size to 10K

- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
* deduplicate actually identical emails. fixes
https://trello.com/c/nLFjEDGH/552-fluidkeys-doesnt-de-duplicate-emails-addresses-properly
* deduplicate case-identical email addresses
e.g. a@example.com, A@example.com
even though the spec says that case does matter (for the part before
the @), in practice very few (if any?) mail hosts actually
differentiate. Fixes
https://trello.com/c/w1pEwccy/662-dont-send-separate-emails-to-different-emails-if-the-only-difference-is-uppercase-lowercase
That said, if a key has John@example.com and john@example.com *and*
John@example.com is marked as primary, we'll retain that one of the two
(because we preserve order, and primary emails are sorted before
non-primary ones)
> deduplicate case-identical email addresses

- fk/secretreceive.go
- fk/secretsend.go
- fk/ui.go
- fk/ui_test.go
`formatFirstTwentyLines` takes an input string and returns the first 20 lines of it plus a boolean of whether it was truncated.
The return string always ends with a trailing new line `\n`: i.e. if input was `line 1\nline2`, it returns `line 1\nline\n`
When receiving a secret, the preview looks like this:
We'd been hardcoding `fileDividerLength` as 80, but since we want to use `formatFileDivider` for previewing secrets, we need to prepend the divider with the no log character. Doing so would make the line > 80 runes long!
By taking a variable we can now account for this.
FormatFileDivider now wants to take a more generic message (i.e. "this preview shows only 20 lines")
> Truncate long secrets

- fk/keymaintain.go
- fk/main.go
rather than down in the key maintain subcommand
we're doing this because we're about to introduce a 2nd occurrence of the
flag and it doesn't make sense to implement twice
> check for cron-output flag at highest level

- script/release
so that we remember to request @rubdos to bump a new version each time
we release!
> release: print url to notify Arch User Repository

- fk/main.go
- fk/team.go
- fk/teamsync.go
- teamroster/teamroster.go
the roster lives in `~/.config/fluidkeys/teams/<whatever>/team.toml` and
looks like this:
``` uuid = "38be2a70-23d8-11e9-bafd-7f97f2e239a3" name = "Fluidkeys CIC"
[people]
[people."paul@fluidkeys.com"]
fingerprint = "B79F 0840 DEF1 2EBB A72F  F72D 7327 A44C 2157 A758"
[people."ian@fluidkeys.com"]
fingerprint = "E63A F0E7 4EB5 DE3F B72D  C981 C991 7093 18EC BDE7"
```
Note that we will cryptographically validate `roster.asc` before release.
> add MVP `fk team sync` with team roster file

- Makefile
so that `make` can actually detect whether things have changed properly
> Makefile: depend on *.go

- fk/keymaintain.go
- gpgwrapper/backup.go
- gpgwrapper/backup_test.go
This code is a hangover from when we used to timestamp the file backup. We don't do this anymore since we put the file in a timestamped directory (as seen in `makeGnupgBackup`).
Comment `gpgwrapper.Backuphomedir` to make this clear.
> stop passing time into gpg.BackupHomeDir

- .gometalinter.json
- Makefile
so we can manually run it with repeatable configuration (even though the
tests don't currently depend on it)
this should get all the dependencies if you're feeling brave:
```
go get -u github.com/zmb3/gogetdoc
go get -u github.com/davidrjenni/reftools/cmd/fillstruct
go get -u github.com/rogpeppe/godef
go get -u github.com/fatih/motion
go get -u github.com/kisielk/errcheck
go get -u github.com/derekparker/delve/cmd/dlv
go get -u github.com/mdempsky/gocode
go get -u github.com/josharian/impl
go get -u github.com/koron/iferr
go get -u github.com/jstemmer/gotags
go get -u github.com/stamblerre/gocode
go get -u github.com/fatih/gomodifytags
go get -u github.com/klauspost/asmfmt/cmd/asmfmt
go get -u github.com/alecthomas/gometalinter
go get -u golang.org/x/tools/cmd/gotype
go get -u …
```
> add `make test_lint` to run `gometalinter`

- fk/keycreate.go
- fk/keymaintain.go
- fk/teamsync.go
- fk/ui.go
This allows us to handle the checkboxes independently, and print a pending
action while asking for permission for terminal to modify the users
crontab.
Split tryEnableMaintainAutomatically > tryStorePassword & tryMaintainAutomatically
> Show pending action before trying to edit crontab

- fk/main.go
- fk/teamcreate.go
- fk/teamcreate_test.go
This command doesn't actually do anything with the information it collects
at this stage. It just prints it back to screen and warns the user that
this feature isn't currently implemented.
> team setup: prompt for team name and members

- fk/main.go
- fk/team.go
`setup` is a reserved command in Fluidkeys. It's a "wizard" that
guides the user through getting started with Fluidkeys.
We `create` other objects: keys, teams, ...
> move `team setup` to `team create`

- fingerprint/fingerprint.go
- fingerprint/fingerprint_test.go
so modules like JSON, toml can convert it into bytes (strings)
note that this is *not* on the pointer receiver
> Fingerprint: implement TextMarshaler interface

- teamroster/teamroster.go
so the toml files comes out as `email` not `Email`
> add TOML annotations to teamroster.People

- fk/teamcreate.go
- team/roster.go
- team/roster_test.go
- team/team.go
- team/team_test.go
We populate the team with the original team creator and any other keys we find in `gpg`.
The file is written into a subdirectory of `.config/fluidkeys/teams` based on the name of the team and a UUID
> Team create: Save the team as `roster.toml` to disk

- team/team_test.go
on the second call to `SignAndSave` (the overwrite), compare the returned
roster and signature to what's been written to disk
> test that read-back roster matches return value

- fk/main.go
- fk/teamauthorize.go
Opted for authorize over authorise since ize is in the Cambridge
Dictionary where ise isn't, and a sense that American's frown
more upose ise, than brits ize.
https://www.quora.com/What-is-the-difference-between-authorise-and-authorize
> add unimplemented `fk team authorize`

- colour/colour.go
- fk/teamcreate.go
- ui/ui.go
- ui/ui_test.go
Instead, provide the admin with an invitation they can copy and paste into a message to people they want to use Fluidkeys with.
We also present the admin with a preview of `roster.toml` and ask them to confirm that they want to sign it.
> Team Create: stop prompting for email addresses of team members

- assert/equality.go
- assert/error_test.go
- fk/secretsend.go
- fk/secretsend_test.go
if got & expected can both be cast to errors, compare them directly *as*
errors, specifically:
* if 2 errors are different type, they're not equal
* otherwise, they're equal if their strings are equal
this is motivated by a change in Go 1.13 that mean errors don't compare
equal using naive reflect.Equal
Bonus: print long errors across different lines
> assert.Equal: treat error types differently

- api/api.go
- api/api_test.go
- fk/teamcreate.go
We always raised an error if this was nil, so I think we should
force a value to be passed.
> dont allow a pointer to fingerprint in UpsertTeam

- api/api.go
- api/api_test.go
- config/config.go
- config/config_test.go
- database/database.go
- database/database_test.go
- exampledata/exampledata.go
- exampledata/exampledata_test.go
- fk/keycreate.go
- fk/keyfromgpg.go
- fk/keymaintain.go
- fk/main.go
- fk/main_test.go
- fk/privatekeys_test.go
- gpgwrapper/gpgwrapper.go
- gpgwrapper/gpgwrapper_test.go
- gpgwrapper/interfaces.go
- gpgwrapper/listpublicparser.go
- gpgwrapper/listpublicparser_test.go
- gpgwrapper/listsecretparser.go
- gpgwrapper/listsecretparser_test.go
- keyring/keyring.go
- keyring/keyring_test.go
- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
- team/roster_test.go
- team/team.go
- team/team_test.go
We should always refer to the `fingerprint` package as `fpr`.
> Refer to the fingerprint package as fpr and value as fingerprint

- team/rostersaver.go
- team/rostersaver_test.go
this lets you do a 2-stage save, with some other (fallible) task in the
middle:
``` rosterSaver := RosterSaver{Directory: teamSubdirectory}
rosterSaver.SaveDraft(roster, signature)
if err := api.UpdateRoster(roster, signature); err != nil {
rosterSaver.DiscardDraft()
}
rosterSaver.CommitDraft()
```
> add RosterSaver

- fk/teamauthorize.go
ui.Formatxxx() adds a newline (\n) at the top of every dialog
box. If we don't have any error, we should make sure we also add
this new line in, so the requests are spaced properly.
Before:
After:
> fix line spacing when itterating over requests

- fk/teamjoin.go
We never double space and ui.PrintCheckboxSuccess includes a \n
at the end.
I noticed this when recording the demo for weeknotes, it looked like this:
> remove extra new line on `team join`

- humanize/duration.go
- humanize/duration_test.go
needed for `fk team sync`:
https://docs.google.com/document/d/1FHQXHP7X8Uvtvn72OqZNVYyFMocrJ2MM1zWtYTM4d0c/edit#heading=h.htvwu2p78dq
> add humanize.RoughDuration, e.g. "1 hour", "5 days"

- api/api.go
- api/api_test.go
this is so that `fk team sync` can handle it as "you don't have access to
this team"
> api.GetTeamRoster: 403: return ErrForbidden

- api/api.go
- api/api_test.go
I'll use this later so that when admins are reviewing requests, they delete them.
> add client.DeleteRequestToJoinTeam

- fk/teamsync.go
this handles the happy path and *most* other paths for joining a new team
(based on requests to join a team)
things to note:
* new rosters are cryptographically validated. this requires downloading
the admin keys from the API by fingerprint. the behaviour for
validating an *update* will be different
* requests time out after 7 days. this is currently implemented in
`fk team sync` but I think I'll move it to database in a subsequent PR
(along with de-duplicating requests)
* requests are deleted from our local db if they succeed
* content should match our Google doc:
https://docs.google.com/document/d/1FHQXHP7X8Uvtvn72OqZNVYyFMocrJ2MM1zWtYTM4d0c/edit#heading=h.htvwu2p78dq
> fk team sync: get & verify new roster & keys

- database/database.go
- database/database_test.go
- database/sort.go
do a bit of test tidy-up:
* delete zero-value initializations: they have no effect, and just distract from the tests
* factor out `now` and `later`
> de-duplicate in RecordRequestToJoinTeam, GetRequestsToJoinTeams

- fk/main.go
- fk/team.go
- fk/teamfetch.go
update content for "fetch" verb: factor out the headline so we use it consistently
> rename `fk team sync` -> `fk team fetch`

- api/api.go
- api/api_test.go
- fk/teamfetch.go
we normally do this by convention for the PgpKey, but specifically:
* it's quite a large struct
* it prevents lots of copies of the private key in memory
* if we *unlock* a PgpKey (with a password) it mutates the object, and
any copies of it therefore aren't unlocked
> api.GetTeamRoster: take pointer to PgpKey

- humanize/duration.go
- humanize/duration_test.go
Now rather than saying "just now ago", it would say "a moment ago".
> make RoughDuration make sense for times of < 1 min

- fk/teamfetch.go
- team/parse.go
- team/parse_test.go
- team/team.go
- team/team_test.go
- user/user_test.go
the motivation here is to make sure the `Team` struct *always* has `roster` and `signature` set.
Previously, teams loaded through `team.LoadTeams` would *not* have it set, nor would teams loaded
through `team.Parse`
Now, there's a new (tested) function called `team.Load(roster, signature)` which parses the team
*and* then sets signature and roster on the struct. I've unexported `parse` so you can only create
a team through `Load`
* add team.Load(roster, signature) & tests
this is going to replace `Parse`, but this one passes through the values of
roster and signature so they're available on the Team struct.
* t.Roster: panic if they're not set. this is a safety check, it shouldn't happen.
* unexport Parse (callers should use Load) instead
* add tests for team.LoadTeams
* refactor …
> replace team.Parse with team.Load

- user/user.go
- user/user_test.go
This means that that calling function can do things like:
```
isInTeam, team, err := user.IsInTeam(uuid)
...
if isInTeam {
fmt.Printf("You're already in %s", team.Name)
}
```
> Make `IsInTeam` return a pointer to the team

- user/user_test.go
because `Team` now has a roster and signature, comparing a team with an
*incomplete* team no longer works.
For tests like this we can compare the team UUID instead.
Also improve test names.
> assert.Equal on team.UUID rather than whole team

- fk/teamcreate.go
- fk/teamjoin.go
- user/user_test.go
Paul's mod: drop the helper function
I _think_ these are the only two ways to create a membership from the
command line. I wonder if I need to also check elsewhere in the
application? For example, what would happen if the user hacked their
`fluidkeys/teams` directory, and duplicated a team subdirectory?
> block `team create` and `join` if already in team

- fk/main.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
before I start proper work on this, fix the bug that meant cron lines
weren't being removed:
https://trello.com/c/Tb2dSSEE
the problem was that we were relying on our cron lines having a trailing
(and leading) newline to be able to detect or remove them. Now the cron
lines can exist any (valid) way in the crontab.
Also improve the appearance of adding crontab lines:
before: "" after: ""# Fluidkeys...\n@hourly...\n"
before: "# some other stuff" after: "# some other stuff\n\n"#
Fluidkeys...\n@hourly...\n"
before: "# some other stuff\n" after: "# some other stuff\n\n"#
Fluidkeys...\n@hourly...\n"
> scheduler: add tests, fix bug

- scheduler/scheduler.go
- scheduler/scheduler_test.go
```
@hourly perl -e 'sleep int(rand(3600))' && /usr/local/bin/fk sync
--cron-output
```
* run new `fk sync` with a random delay
* remove the old cron lines from the user's crontab
> scheduler: update cron lines

- fk/teamfetch.go
previously we were handling new and updated teams separately (2 places to fetch keys, etc)
this PR simplifies it so we always do:
1. handle requests to join teams
2. load our teams (including those from 1.) and update them
> team fetch: simplify

- fk/privatekeys.go
- fk/privatekeys_test.go
- gpgwrapper/interfaces.go
- pgpkey/interfaces.go
use the new GnuPG.TrustUltimately method to configure GnuPG's ownertrust
database that we should trust our own signatures on other peoples' keys.
> trust our own keys when we push them back into gpg

- Gopkg.lock
- Gopkg.toml
- pgpkey/certify.go
- pgpkey/certify_test.go
- vendor/github.com/fluidkeys/crypto/openpgp/packet/signature.go
can't merge before https://github.com/fluidkeys/crypto/pull/10
this creates non-exportable (local only) certification signatures of keys.
when imported into GnuPG, it shows those keys as valid / trusted.
> add PgpKey.CertifyEmail()

- database/database.go
- database/database_test.go
- fk/main.go
- fk/status.go
- fk/teamfetch.go
- table/keytable.go
- table/keytable_test.go
- table/peopletable.go
- table/table.go
- table/table_test.go
This PR handles all of a user's memberships, or rather all keys they are members of a team with.
If prints something that looks like this:
> `fk status`: Print keys and team members for memberships

- fk/teamfetch.go
- pgpkey/certify.go
We were also swallowing the value of the error
> fix bug where emails without <> didn't match

- database/database.go
- database/database_test.go
This lets us test whether something's "stale", e.g. whether the roster
was last updated more than 24 hours ago
> add database.IsOlderThan

- fk/status.go
in the same way as:
https://github.com/fluidkeys/fluidkeys/pull/464/commits/089fd7b89744cacfa541f756350894fe7ec1fc08
`fk status` can't claim our request hasn't been approved: only
`fk team fetch` can.
before:
after:
> fk status: don't be misleading about not approved

- fk/teamapply.go
requires #463
if someone tries to join a team that they've already got a request to join,
it gave the warning including:
> The admin hasn't authorized this yet.
But that's misleading, since they might have authorized it, and we haven't
run `fk team fetch`
Replace those words with a hint to try `fk team fetch`
> team apply: don't make misleading claim

- policy/policy.go
- policy/policy_test.go
- status/actions.go
- status/actions_test.go
- status/keyactions.go
- status/keywarning.go
- status/keywarning_test.go
- status/status.go
- status/status_test.go
after extensive testing, we've realised the world isn't ready for fast-expiring PGP keys!
this PR introduces the following changes:
1. keys last ~1 year
previously, keys expired 30 after 1st of next month
now, keys expire in 1 year *rounded* to the next quarter (1st feb, may, august or november)
This means there will only be 4 dates in the year when expiries occur, allowing teams to
help each other out 
2. extend (don't rotate) subkeys
creating new subkeys can cause trouble with multiple devices, and using a single password
for primary & subkeys is a false sense of security.
instead, just extend subkeys the same as the primary key
3. start trying to extend 60 days before the expiry date (previously it was 30)
so if your expiry date is 1st May, on 2nd March (60 days before), fk will start …
> extend keys annually & extend (don't rotate) subkeys

- database/database.go
- database/database_test.go
any struct that implements the interface `fmt.Stringer` by defining
.String()
I need this to be able to record that key A was certified by key B. I need
both bit of information, not just one, so I'll implement a struct
`recordOfCertification` whose `String()` method returns e.g.
`aaa-certified-by-bbb`
> GetLast, RecordLast: supporting anything with .String (a 'Stringer')

- apiclient/apiclient.go
- apiclient/apiclient_test.go
- fk/init.go
- fk/keycreate.go
- fk/keyupload.go
- fk/main.go
- fk/secretreceive.go
- fk/secretsend.go
- fk/setup.go
- fk/teamapply.go
- fk/teamauthorize.go
- fk/teamcreate.go
- fk/teamfetch.go
1. rename `api` package to `apiclient`: it's not an api, it's a client of an API!
2. rename global `client` -> `api` in `fk/main.go`
this allows the more natural feeling `api.GetPublicKey(..)`
3. rename `apiclient.NewClient` -> `apiclient.New`
> rename api / client / apiclient

- database/database.go
- database/database_test.go
- fk/teamfetch.go
the end goal here is that *normally*, `fk sync` doesn't require an unlocked
key.
that's good because:
1. we shouldn't unlock a key if it's not strictly necessary
2. we can add error reporting to the unlock key routine, and we'll only
see errors when they actually matter (e.g. a new team member has
joined the team, and their key needs certifying)
We use the database `GetLast` / `RecordLast` functions to remember that we've certified
an (email / key / certifier) combination.
> team fetch: only certify keys once

- ui/ui.go
This allows you to do:
```
ui.RunWithCheckboxes("important action", func() error {
return ui.SkipThisAction
})
```
and it'll print the skipped checkbox instead of the error one.
> ui.RunWithCheckboxes: support skipping from inside

- fk/teamfetch.go
the first time we successfully unlock a key, cache the result so we
don't need to unlock it again in subsequent calls.
> team fetch: getUnlockedKey: if already unlocked, don't prompt

- fk/teamfetch.go
this is to give us visibility of whether the fk client is running reliably
from the scheduler for teams.
> team fetch: log success and failure in unattended mode

- fk/keymaintain.go
- fk/main.go
- scheduler/cron.go
- scheduler/cron_test.go
- scheduler/filehelpers.go
- scheduler/interfaces.go
- scheduler/launchd.go
- scheduler/launchd_test.go
- scheduler/scheduler.go
I made a schedulerInterface and seperated out cron and launchd.
We check for `launchd` in the init() of the scheduler package
to figure out whether to pass through to launchd or cron.
> Introduce launchd

- fk/keycreate.go
- fk/keymaintain.go
- keyring/keyring.go
We do this on both `key create` and `key from-gpg`, but only if the keyring
backend is KeyChain.
This is how it looks on macOS.
For *key create*:
For *key maintain*:
> Instruct to allow keychain access

- fk/teamapply.go
if you've trashed your `teams/team` subdirectory, previously it was difficult to rejoin a team.
Assumption: you're listed in the team roster on the API.
Scenarios:
1. no requests to join team in local DB or in API
2. got a request to join team in local DB but *not* in the API
3. no request to join team in local DB but *got one* in the API
4. got request to join team in local DB and in the API
If you've got a local request already, it presents an infobox with your verification details
you need to give the admin.
For this scenario the solution is running `fk team fetch`. I've moved the call to action (run `fk
team fetch`) to the bottom so it's clearer.
tricker because the API rejects your request to join the team, saying
'Failed to apply: Already got request'
Now, we store a request in the …
> enable re-joining a team you've deleted

- scheduler/cron.go
- scheduler/scheduler.go
if we've just enabled launchd for the first time, we try and remove legacy
crontab lines.
If and only if the cron lines were actually present, print a permissions
primer and checkbox before trying to remove them.
This prevents the situation where someone types `fk` and all they see is a
permissions dialog asking to "administer the computer". At least they'll
get some heads-up about why.
> on launchd enable, notify before editing crontab

- fk/teamfetch.go
fail more gracefully than a nil pointer error
https://github.com/fluidkeys/fluidkeys/issues/502
this bug was introduced in 451c6182f698b5a0a7ef6dd81480e358c9ecc364
> team fetch: don't continue if failed to fetch key

- database/database.go
- database/database_test.go
- database/sort.go
- fk/teamapply.go
previously it was possible that the local DB has a request to join a team, but the API doesn't
that makes it impossible to re-request to join the team, *and* for an admin to authorize the person
these changes:
1. make it less likely the mismatch will occur in the first place
2. make it recoverable if that does occur
> `team apply`: don't get stuck unable to join a team

- team/team.go
- team/team_test.go
- team/validateupdate.go
- team/validateupdate_test.go
when the user is editing a team, we want to make sure they don't make the
team unusable (like changing the UUID, removing all admins etc)
This function codifies those rules.
> add team.ValidateUpdate(before, after, me)

- fk/teamauthorize.go
- team/team.go
- team/team_test.go
for some reason it was returning error before value, giving linter
errors
> GetUpsertPersonWarnings: flip return args
