- Makefile
It also replaces `make homebrew_install`
> Add `make install` which actually works

- Makefile
- colour/LICENSE
- colour/colour.go
- colour/constants.go
- fluidkeys/main.go
* Add colour package, adapted from https://github.com/amulyakashyap09/colors - thanks @amulyakashyap09 for the headstart :)
* Add diceware dependency
> Display a diceware-esque password with prompt

- README.md
> Add to README that you need Go 1.10 and dep

- gpgwrapper/gpgwrapper.go
- gpgwrapper/gpgwrapper_test.go
- gpgwrapper/parser.go
* Add parseListSecretKeys and tests
* Add parseFingerprint and tests
* Add parseTimestamp and tests
> Add GnuPG.ListSecretKeys, returning []SecretKeyListing

- fluidkeys/main.go
- fluidkeys/main_test.go
- humanize/plural.go
- humanize/plural_test.go
We list the secret keys in GPG, then prompt the user to select which to import.
At present this just prints it back.
> Introduce `key from-gpg`

- Makefile
(We might want to have travis use -v, but don't care atm)
> Don't run go test with -v

- fluidkeys/main.go
This does 3 things:
1. gets the linked fingerprints from the db
2. asks gpg for the public key for each one
3. tries to load a PgpKey from the armored public key for each one
> Add main.loadPgpKeys

- Makefile
- fluidkeys/main.go
- keytableprinter/keytableprinter.go
- keytableprinter/keytableprinter_test.go
At the moment, we print the 'Next rotation' header, but aren't checking these values for each key.
> Print the keys managed by fluidkeys with `key list`

- assert/equality.go
- assert/equality_test.go
I've done this a lot, and anticipate doing a lot more of it. Now felt as good a time as any to create a helper :)
> Assert equal slices of strings

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/fluidkeys/crypto/acme/autocert/example_test.go
- vendor/github.com/fluidkeys/crypto/chacha20poly1305/chacha20poly1305_amd64.go
- vendor/github.com/fluidkeys/crypto/openpgp/keys.go
- vendor/github.com/fluidkeys/crypto/openpgp/keys_test.go
- vendor/github.com/fluidkeys/crypto/ssh/keys.go
- vendor/github.com/fluidkeys/crypto/ssh/keys_test.go
This contains [the fix](https://github.com/fluidkeys/crypto/pull/6)
required to make my subkeys work properly.
> Point to newer tag of fluidkeys/crypto

- exampledata/exampledata.go
- exampledata/exampledata_test.go
- status/status.go
- status/status_test.go
I've created a really specific key here to pin the bug. Let me know if the test suite you're building makes this redundant.
> Fix warnings for a key with a subkey nearing expiry

- pgpkey/expiry.go
- pgpkey/expiry_test.go
- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
- pgpkey/sort.go
- status/status.go
- status/status_test.go
EncryptionSubkey returns the most recent valid subkey.
As part of making this we've introduced lots of tests around what a "valid"
subkey is.
> add Pgpkey.EncryptionSubkey() and tests

- keytableprinter/keytableprinter.go
printTopLevelHint prints a single hint to suggest the user should run`fk key rotate` if any of their keys are due or overdue for rotation.
> Print a hint to user on `fk key list`

- fluidkeys/main.go
Turns out there's an `init()` function which runs before main! So this is a
pretty good place to do this stuff.
> initialize gpg, db and fluidkeys directory once

- fluidkeys/main.go
This is hugely dependent on the other pull requests (#102 #99 #98 #97 #96), but
I wanna get it out there ready!
> Implement `fk key rotate --dry-run`

- status/actions.go
- status/keyactions.go
- status/keywarning.go
- status/status.go
This involved introducing `CurrentValidUntil` on `KeyWarning`, so as to be able to tell whether we're *lengthen*ing or *shorten*ing the key in our action.
> Make action strings reflect the designs in google docs

- policy/policy.go
* AcceptablePreferredSymmetricAlgorithms
* SupportedSymmetricKeyAlgorithms
* AcceptablePreferredHashAlgorithms
* SupportedHashAlgorithms
* AcceptableSignatureHashes
> add new things to policy

- colour/colour.go
- colour/colour_test.go
- colour/constants.go
- fluidkeys/keyrotate.go
- fluidkeys/main.go
- fluidkeys/main_test.go
- keytableprinter/formatwarnings.go
- keytableprinter/formatwarnings_test.go
- keytableprinter/keytableprinter.go
- keytableprinter/keytableprinter_test.go
I was getting in a bit of a muddle with whether we refer to colours by
actual colour or abstract style and have opted to export only abstract
style functions like 'Info', 'Warning', or 'Success'. These are then
defined within Colour itself.
> Improve the public interface to Colour

- openpgpdefs/compression/compression.go
- pgpkey/pgpkey.go
- status/actions.go
- status/actions_test.go
- status/keyactions.go
- status/status.go
* SetPreferredSymmetricAlgorithms
* SetPreferredHashAlgorithms
* SetPreferredCompressionAlgorithms
* RefreshUserIdSelfSignatures
* RefreshSubkeyBindingSignature
Also rename RevokeSubkey -> ExpireSubkey
> add 5 KeyAction types (without implementation)

- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
- policy/policy.go
- status/keyactions.go
New methods in PgpKey:
* SetPreferredSymmetricAlgorithms(...)
* SetPreferredHashAlgorithms(...)
* SetPreferredCompressionAlgorithms(...)
* RefreshUserIdSelfSignatures(...)
* RefreshSubkeyBindingSignature(...)
> implement KeyActions in PgpKey

- pgpkey/pgpkey.go
- pgpkey/pgpkey_test.go
This uses the new `policy.SignatureHashFunction` everywhere where self signatures are currently created
> use new SHA512 hash policy

- pgpkey/pgpkey.go
rebase after merging #135 #136 #137
rather than setting all these preferences, expiry etc manually, use the
methods we now have:
* SetPreferredSymmetricAlgorithms
* SetPreferredHashAlgorithms
* SetPreferredCompressionAlgorithms
* UpdateSubkeyValidUntil
* UpdateExpiryForAllUserIds
> refactor generateKeyOfSize: use new methods

- fluidkeys/keyrotate.go
- fluidkeys/main.go
* Print the options depending on defaultValue passed to `promptYesOrNo`
> Make promptYesOrNo take defaultInput rather than defaultResult

- fluidkeys/keyrotate.go
Rebase after https://github.com/fluidkeys/fluidkeys/pull/154
> Prompt to automatically rotate successfully rotated keys

- Makefile
- config/config.go
- config/config_test.go
- fluidkeys/main.go
- fluidkeys/ui.go
- scheduler/scheduler.go
* add scheduler.Enable, Disable
* enable or disable cron (scheduler) from init
* add Config.RunFromCron()
* add Config.Filename()...
* add ui.go with printInfo ... this is a small step to factoring out some of the UI components
> add fluidkeys to user's crontab

- out/out.go
> Add init to out, setting output to terminal

- Makefile
- colour/colour.go
- fluidkeys/keycreate.go
- fluidkeys/main.go
- fluidkeys/ui.go
Using checkboxes for the various actions is more consistent with the
overall design of Fluidkeys.
> Redesign `key create` post design crit

- fluidkeys/privatekeys.go
- gpgwrapper/gpgwrapper.go
and link to our webpage [fluidkeys.com/tweak-gpg-2.1.11/](https://fluidkeys.com/tweak-gpg-2.1.11/)
> detect gpg 2.1.11 pinentry mode 'loopback' error

- fluidkeys/keymaintain.go
> tweak appearance of final error output

- fluidkeys/keymaintain.go
... as it causes cron the think the job failed, and send emails
> don't output stray newline in cron mode

- gpgwrapper/gpgwrapper.go
we used to pass in *combined* stdout and stderr to this function, and it
would check for the "nothing exported" error in the combined output.
when we split stdout and stderr, we stopped passing in stderr, so it
couldn't ever be detected.
> gpg_wrapper: reinstate check for "nothing exported"

- Makefile
- fluidkeys/init.go
- fluidkeys/keycreate.go
- fluidkeys/keyfromgpg.go
- fluidkeys/main.go
* move init functions into fluidkeys/init.go
* un-factor-out constant strings in keycreate
* move PromptWhichKeyFromGPG into fluidkeys/keyfromgpg
* move DicewarePassword / generatePgpKeyResult - these should've been moved into fluidkeys/keycreate.go before
* move ensureCrontabStateMatchesConfig below main
> move code out of fluidkeys/main.go

- Makefile
- api/api.go
- fluidkeys/main.go
- fluidkeys/secretreceive.go
This subcommand makes an API client call `client.ListSecrets`, and
then attempts to decrypt the content of these secrets against a key.
> Introduce `secret receive`

- api/api.go
- fluidkeys/secretreceive.go
I've decided to delete a secret on the server whether it successfully
decrypts or not. I'm not sure what good it'd be to keep it on the server if
it's failed to decrypt?
Also, if we fail to either decode the metadata (for the UUID), or to
actually delete the secret on the server I've opted to log this.
> Delete secrets when downloading

- api/api.go
- api/api_test.go
- fluidkeys/init.go
- fluidkeys/keypublish.go
- fluidkeys/main.go
- fluidkeys/secretreceive.go
- fluidkeys/secretsend.go
... And factor out the initialisation of client.
> Pass version to NewClient for appending to user-agent

- fluidkeys/secretsend.go
so that we don't prompt someone, then disappoint them.
Also, test we can actually encrypt to the key before prompting using dummy secret data.
> check for key *before* prompting for secret

- config/config.go
- config/config_test.go
- fluidkeys/keycreate.go
- fluidkeys/keymaintain.go
Note the `automaticResponder` will simply check the config file.
* Rename AllowSearchByEmail > PublishToAPI for clarity
> Prompt user whether they want to publish their key during `key maintain`

- fluidkeys/keycreate.go
- fluidkeys/keymaintain.go
> Don't call promptYesNo with nil key

- api/api.go
Fixes the bug where the API's "detail" response is never actually
decoded.
Before, the `Decode()` call inside `decodeErrorResponse` would *always*
return the error "http: read on closed response body". This is because
of the `defer response.Body.Close()` inside `do`.
That means that only `do` has the chance to read `response.Body`.
Rather than having every function inspect `response.StatusCode` and
choose to call `makeErrorForAPIResponse`, call it directory from inside
`do` (IF the response code was a failure, e.g. not 2xx)
> Client: call makeErrorForAPIResponse inside do()

- api/api.go
to make it a *lot* easier to hack on locally
> use env variable FLUIDKEYS_API_URL

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/godbus/dbus/conn_darwin.go
- vendor/github.com/godbus/dbus/object.go
don't use our fork any more since it's been merged into upstream.
> switch back to github.com/godbus/dbus

- Makefile
- backupzip/backupzip.go
- config/config.go
- fingerprint/fingerprint.go
- fluidkeys/init.go
- fluidkeys/keycreate.go
- fluidkeys/keymaintain.go
- fluidkeys/keypublish.go
- fluidkeys/main.go
- fluidkeys/password.go
- fluidkeys/secretsend.go
- keyring/passwordfile.go
- pgpkey/pgpkey_test.go
- script/test_lint
- status/status.go
if we simply `panic` our debug log file doesn't contain any clue of what
happened.
also, add script/test_lint to detect `panic` creeping in to future code
> panic(..) -> log.Panic[f](...)

- fluidkeys/secretsend.go
☝️ Looks a bit weird, removing the break fixes this!
> Remove double line break reporting key found

- fluidkeys/secretreceive.go
If we fail to delete a secret, we log it, but carry on.
> Prompt to delete secrets

- Makefile
- colour/colour.go
- fluidkeys/keycreate.go
- fluidkeys/main.go
- fluidkeys/setup.go
This wraps `key create` with a friendly welcome, and then sends them a test secret.
> Introduce `fk setup`

- fluidkeys/secretsend.go
@paulfurley can you check whether that emoji displays correctly on your machine, please?
> Add encryption info when sending secret

- fluidkeys/secretsend.go
Merge https://github.com/fluidkeys/www.fluidkeys.com/pull/66 when we release `fk setup` in 0.3
> Print a friendly invite message if the key is not found in api

- fluidkeys/keyupload.go
as a hint that it's going to change the config
> "Upload key from now on?"

- .github/ISSUE_TEMPLATE.md
* Don't bother linking to Trello, it's a burden.
* Make the list a little easier to adapt.
* Ask for debug log outpu
> Simplify Github issue template

- colour/colour.go
- fk/setup.go
It was confusing a user as they then expected other secrets to also
appear in orange.
> stop printing squirrel's secret in organge

- archiver/archiver.go
- archiver/archiver_test.go
- backupzip/backupzip.go
- fk/init.go
- fk/keymaintain.go
if directories don't exist, and we fail to make them, don't just carry on!
* on fluidkeys init (fluidkeys directory)
* archive.MakeFilePath
> check for errors when making directories

- fk/secretreceive.go
- fk/secretreceive_test.go
- pgpkey/decrypt.go
We've factored `downloadAndDecryptSecrets` into `downloadEncryptedSecrets` and `decryptSecrets`.
We've added tests for `decryptAPISecret` and `downloadEncryptedSecrets`.
> factor out downloadEncryptedSecrets and decryptSecrets

- fk/keycreate.go
- fk/keycreate_test.go
> dont panic if matching email for key exists on api

- fk/secretsend.go
- fk/secretsend_test.go
- fk/ui.go
- fk/ui_test.go
> Improve the user interface on `secret send`

- fk/secretsend.go
> export SecretMaxSizeBytes constant

- fk/secretsend.go
- policy/policy.go
so the API doesn't have to bring in all of fk's dependencies :\
> move SecretMaxSizeBytes to policy

- api/api.go
- config/config.go
- database/database.go
- fk/password.go
- fk/secretsend.go
- gpgwrapper/gpgwrapper.go
- pgpkey/pgpkey.go
- scheduler/scheduler.go
* keyring: log failure on purge or save password
these errors aren't fatal, so just log that we saw them and continue
* check for errors and pass up in various places
* change 2 instances of `w.Write([]byte(<string>))` to `io.WriteString(w, <string>)`
> add missing error checks

- colour/colour.go
- fk/keymaintain.go
- fk/main.go
- scheduler/interfaces.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
- ui/ui.go
- ui/ui_test.go
* add new package ui: FormatFailure, FormatWarning
* improve crontab error messages on writeCrontab
* extract runCrontab into interface for mocking later
> don't panic on cron error (print pretty message)

- teamroster/teamroster.go
while we're at it, add comments to exported things in teamroster
> teamroster: export Parse so API can use it

- fk/teamsync.go
- teamroster/teamroster.go
- teamroster/teamroster_test.go
* add Email to Person
* use Array of Tables (list of maps) instead of map[email] ->
fingerprint
* add test
> Restructure team roster

- fk/teamcreate.go
> Team create: prompt for which team email address to use

- fk/teamcreate.go
> Add padding to account for checkbox when printing roster path

- team/roster.go
- team/roster_test.go
- team/team.go
Return as string, as this was what we always wanted anyway.
> move serialize > Roster

- fk/keycreate.go
note that this will be displayed for *all* routes into `key create`
> "What's your *team* email address?"

- fk/teamcreate.go
- fk/teamjoin.go
* factor out common `getKeyForTeam`
* team create: use new getKeyForTeam
> team join: prompt for key (or drop into create)

- fk/teamcreate.go
- team/roster_test.go
- team/team.go
- team/team_test.go
We'll need to bump the package on `fluidkeys/api` too, so it can parse the incoming toml file.
> record administrators in Team

- database/database.go
- database/database_test.go
This is in preparation for using it to also record which teams
a user has requested to join.
> Start making database more general

- fk/teamauthorize.go
- team/team.go
- team/team_test.go
this brings in a lot of work about showing warnings about conflicts (eg adding a team member who
already has an existing key)
> show requests to join team, prompt to authorize

- fk/teamcreate.go
* use new RunWithCheckboxes
* factor out formatRosterPreview
> slightly refactor team create

- fk/teamcreate.go
requires #385
if the team can't be updated in the API, don't write out the roster after
all
> promptAndSignAndUploadRoster: use 2-stage save

- team/rostersaver.go
- team/rostersaver_test.go
> DiscardDraft: delete directory if it's empty

- database/database.go
- database/database_test.go
- fk/teamjoin.go
- team/team.go
needed for `fk team sync` to display the name of a team we haven't yet
joined
> record team name in request to join team

- ui/ui.go
- ui/ui_test.go
to match the design in `fk team sync`:
https://docs.google.com/document/d/1FHQXHP7X8Uvtvn72OqZNVYyFMocrJ2MM1zWtYTM4d0c/edit#heading=h.htvwu2p78dq
> add ui.FormatSuccess

- fk/teamsync.go
it returns a message like "You requested to join Kiffix 4 days ago."
now #398 can use it :)
> add formatYouRequestedToJoin helper

- database/database.go
...introduced in 142afe9c
note that error strings should begin with lowecase
> fix Golint errors

- config/config_test.go
- database/database_test.go
- gpgwrapper/gpgwrapper_test.go
* database_test.go
* config_test.go
* gpgwrapper_test.go
> use testhelpers.Maketemp

- fk/teamjoin.go
This should be fine, now that https://github.com/fluidkeys/fluidkeys/pull/411 is in.
> team join: you've already requested to join that team

- fk/teamjoin.go
replaces #417
(I'm working mostly offline so I can't tell if you've made these changes already @idrysdale!)
* rebased against master
* use success dialog with no extra lines
* fix spacing
> team join: you're already in that team

- fk/teamfetch.go
- user/user.go
- user/user_test.go
Use this, instead of `database.GetRequestsToJoinTeams()`
> Add user.RequestsToJoinTeams

- fk/main.go
- fk/sync.go
this just wraps 2 commands:
* `fk key maintain automatic`
* `fk team fetch`
> add `fk sync` command

- database/database.go
- database/database_test.go
These functions can be used to record when certain actions get performed on certain items.
This PR supports:
* fingerprints and keys (which are treated the same)
* teams
> Add db.RecordLast and GetLast

- gpgwrapper/gpgwrapper.go
- gpgwrapper/trust.go
- gpgwrapper/trust_test.go
we call this on our own keys to tell GnuPG to believe our own signatures
on other people's keys(!)
> gpgwrapper: add TrustUltimately

- fk/status.go
- fk/teamfetch.go
> `fk status`: Print requests to join teams

- fk/teamfetch.go
if we're running in *unattended* mode (e.g. from cron via `fk sync`)
(if we're running `fk team fetch` directly then *always* download updates)
> team fetch: only update roster & keys every 24hrs

- fk/teamcreate.go
We haven't implemented this yet, so don't reference it.
> UI: Drop reference to `team from-gpg`

- fk/teamcreate.go
* Add pricing info
* Revise list of instructions in invitation
(note it still refers to command `team join`, another pull request will rename this command to `apply`)
> UI: `team create`: implememnt new design

- fk/status.go
- user/user.go
- user/user_test.go
> `fk status`: Print orphaned keys

- fk/teamapply.go
* dont print checkbox about `Request to join...`
* add info box telling user to reply
* print message to apply with
* prompt to copy this message to clipboard
> Implement redesign of `team apply`:

- fk/status.go
help the user recover from "Failed to load key" message by signposting
their db.json file
> factor out formatFailedToLoadKey, add help text

- fk/teamauthorize.go
* tweak how verification details are displayed
* add intro line to roster
* team authorize: move infobox below header + line
as per
https://docs.google.com/document/d/1FHQXHP7X8Uvtvn72OqZNVYyFMocrJ2MM1zWtYTM4d0c/edit#heading=h.lmuuqht68ej1
> team authorize: implement new design

- fk/teamapply.go
if someone requests to join a team, but doesn't copy their verification
details, the admin can't authorize them *and* the user couldn't get the
verification details again.
https://github.com/fluidkeys/fluidkeys/pull/462 introduced in `team
authorize` a hint:
> if you haven't received the verification details, [..] and ask them to
> apply to join the team again
this commit means that if they do try to join the team again, they
actually see the verification details rather than a (unhelpful) warning
> re-print verification deets on 2nd apply

- fk/password.go
I've confirmed this works great from cron.
I've added a [tech debt card](https://trello.com/c/bV1vlFM6) to give `password.go` some love.
> nag to start saving your password, if not already

- fk/teamauthorize.go
* make instructions refer to verification details and be clearer what we mean by "check"
* "Authorize keys" -> "Authorize requests to join ...
> team authorize: if "no", prompt to reject request

- fk/secretsend.go
- fk/secretsend_test.go
> rename 'message' to 'secret'

- fk/status.go
rather than "Invite others to join the team"
> "Invite others to join <name>"

- database/database.go
- database/database_test.go
It's a nasty smell that we had 2 essentially identical switch statements
which can get out of sync.
> factor makeMapKey out of GetLast, RecordLast

- Gopkg.lock
- Gopkg.toml
https://github.com/fluidkeys/api/commit/04f58d76b5b52d547abc362c43cd911b54981e5d
(as mentioned in a14103a6b1d816acca16db5adb8fed7e9acbc569)
> point Gopkg at api latest commit on master

- fk/teamfetch.go
only unlock the key if we actually need it to certify a new key
(I'm getting blocked by all these dependency pull requests)
> team fetch: don't unlock key unless required

- fk/teamfetch.go
before:
``` Fetching and signing keys for other members of Tina's new gang:
[✔] mark@example.com
│ ✔ Successfully fetched keys and imported them into GnuPG
```
after:
``` Fetching and signing keys for other members of Tina's new gang:
[✔] mark@example.com: fetch key
[✔] mark@example.com: sign key
[✔] mark@example.com: import into gpg
│ ✔ Successfully fetched keys and imported them into GnuPG
```
although it's wordier, it helps to see what's going on, which is reassuring
if it's about to prompt you for a password.
> split fetch, sign, import into 3 checkboxes

- Gopkg.lock
- Gopkg.toml
- apiclient/apiclient.go
- apiclient/apiclient_test.go
- apiclient/event.go
- vendor/github.com/fluidkeys/api/v1structs/v1structs.go
so we can send log messages to the server, for example that something went
wrong updating a team
> api.Log(event)

- fk/teamauthorize.go
- fk/teamcreate.go
@idrysdale I'd appreciate some good testing on this one!
> promptAndSignAndUploadRoster: use getUnlockedKey

- fk/teamauthorize.go
(rebase after #489)
this was built before we had the nice `user.Memberships()` function.
remove getTeamsOfWhichImAdmin, teamAndKey
introduce filterByAdmin to turn *all* team memberships into memberships
where I'm an admin.
> team authorize: refactor to use user.Memberships()

- fk/teamauthorize.go
- fk/teamcreate.go
> after authorizing new members fetch & certify keys

- fk/teamapply.go
every 30 seconds to see if we've been added to the team yet.
after 4 hours, give up.
either way, run `fk team fetch` afterwards
> after `fk team apply`, keep checking

- status/keyactions.go
... and factor out into a const to make it harder to miss next time
> fix 2-digit year format

- fk/teamapply.go
> remove hardcoded kiffix teamname
